"""add source_state table

Revision ID: c503b386ce5e
Revises: 2a0b7b569986
Create Date: 2026-04-13 17:24:07.187657

Phase 4 D-04: per-source ingest health + conditional-GET cache.
Columns: name PK, etag, last_modified, consecutive_failures (int NOT NULL
DEFAULT 0), disabled_at TIMESTAMPTZ, last_fetched_at TIMESTAMPTZ,
last_status. Roundtrip verified by
tests/integration/test_source_state_repo.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c503b386ce5e'
down_revision: Union[str, Sequence[str], None] = '2a0b7b569986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_state',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_state')
    # ### end Alembic commands ###
