"""initial schema: articles, clusters, posts, run_log

Revision ID: 2a0b7b569986
Revises:
Create Date: 2026-04-13 09:25:49.449843

Per D-02: autogenerated + post-edited. Covers STORE-01..06.

Post-edit audit:
  - Verified TIMESTAMPTZ on every datetime column (fetched_at, published_at,
    started_at, finished_at, created_at, posted_at)
  - Verified LargeBinary → BYTEA on posts.theme_centroid (D-07)
  - Verified CHAR(64)/VARCHAR(64) + UNIQUE on articles.article_hash (D-06)
  - Verified postgresql.JSONB on run_log.counts + clusters.centroid_terms
  - Verified postgresql.ARRAY(BigInteger) on clusters.member_article_ids
  - Verified postgresql.ARRAY(Text) on posts.hashtags
  - Verified CHECK ck_posts_status over {pending, posted, failed, dry_run}
  - Verified partial index ix_posts_posted_at_48h with IS NOT NULL clause
  - Downgrade drops children first: posts → clusters → run_log → articles
    (articles has no FK dependency on run_log, safe ordering)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a0b7b569986'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('article_hash', sa.String(length=64), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_hash')
    )
    op.create_index('ix_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('ix_articles_source_fetched_at', 'articles', ['source', 'fetched_at'], unique=False)
    op.create_table('run_log',
    sa.Column('cycle_id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cycle_id')
    )
    op.create_table('clusters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cycle_id', sa.Text(), nullable=False),
    sa.Column('member_article_ids', postgresql.ARRAY(sa.BigInteger()), server_default='{}', nullable=False),
    sa.Column('centroid_terms', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('chosen', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['run_log.cycle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clusters_cycle_id', 'clusters', ['cycle_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cycle_id', sa.Text(), nullable=False),
    sa.Column('cluster_id', sa.BigInteger(), nullable=True),
    sa.Column('theme_centroid', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('tweet_id', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('synthesized_text', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'posted', 'failed', 'dry_run')", name='ck_posts_status'),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cycle_id'], ['run_log.cycle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_cycle_id', 'posts', ['cycle_id'], unique=False)
    op.create_index('ix_posts_posted_at', 'posts', ['posted_at'], unique=False)
    op.create_index('ix_posts_posted_at_48h', 'posts', ['posted_at'], unique=False, postgresql_where=sa.text('posted_at IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_posted_at_48h', table_name='posts', postgresql_where=sa.text('posted_at IS NOT NULL'))
    op.drop_index('ix_posts_posted_at', table_name='posts')
    op.drop_index('ix_posts_cycle_id', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_clusters_cycle_id', table_name='clusters')
    op.drop_table('clusters')
    op.drop_table('run_log')
    op.drop_index('ix_articles_source_fetched_at', table_name='articles')
    op.drop_index('ix_articles_published_at', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
